package com.tk.fcmb.Enums;

public enum ProcessType {

    UPDATE_TRANSACTION_LIMIT,
    UPGRADE_MOBILE_APP_USER_TYPE,
    UPDATE_MOBILE_NUMBER,
    RESET_MOBILE_USER_PASSWORD,
    CLEAR_IMEI,
    BLOCK_USER,
    UNBLOCK_USER,
    RESET_PIN

}
